name: VSIX

on:
  workflow_dispatch:
  push:
  release:
    types: [published]
  pull_request:

jobs:
  build:
    name: CI
    env:
      VSIX_MAJOR: 0.4.0
      DOTNET_VERSION: 6.0.100
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: git submodule update --init --recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Setup .NET 6
      run: |
        export PATH="$(DotNet.Root):$(DotNet.Tools):$PATH"
        curl -L https://raw.githubusercontent.com/dotnet/install-scripts/7a9d5dcab92cf131fc2d8977052f8c2c2d540e22/src/dotnet-install.sh > dotnet-install.sh
        sh dotnet-install.sh --version $DOTNET_VERSION --install-dir $DOTNET_ROOT --verbose
        dotnet --list-sdks
        echo "##vso[task.setvariable variable=PATH]$PATH"
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Version (Release)
      if: github.event_name == 'release'
      run: |
        arrTag=(${GITHUB_REF//\// })
        VERSION="${arrTag[2]}"
        echo "::set-output name=pkgverrelease::$VERSION"
        echo "VSIX VERSION: $VERSION"
    - name: Version (CI)
      if: github.event_name != 'release'
      run: |
        VERSION=$VSIX_MAJOR-ci$GITHUB_RUN_ID
        echo "::set-output name=pkgverci::$VERSION"
        echo "VSIX VERSION: $VERSION"
    - name: NPM
      run: |
        npm install
        npm version $VERSION --git-tag-version false
    - name: Create VSIX
      run: pwsh ./build.ps1 all
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: VSIX
        path: '*.vsix'

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: VSIX
      - name: Version (Release)
        run: |
          arrTag=(${GITHUB_REF//\// })
          VERSION="${arrTag[2]}"
          echo "::set-output name=pkgverrelease::$VERSION"
          echo "VSIX VERSION: $VERSION"
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ./VSIX/vscode-comet.vsix
          packagePath: ""
