name: VSIX

on:
  pull_request:
  push:
jobs:
  build:
    name: CI
    env:
      VSIX_MAJOR: 0.4.0
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: git submodule update --init --recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Version (Release)
      if: github.event_name == 'release'
      run: |
        arrTag=(${GITHUB_REF//\// })
        VERSION="${arrTag[2]}"
        echo "::set-output name=pkgverrelease::$VERSION"
        echo "VSIX VERSION: $VERSION"
    - name: Version (CI)
      if: github.event_name != 'release'
      run: |
        VERSION=$VSIX_MAJOR-ci$GITHUB_RUN_ID
        echo "::set-output name=pkgverci::$VERSION"
        echo "VSIX VERSION: $VERSION"
    - name: NPM
      run: |
        npm install
        npm version $VERSION
    - name: Create VSIX
      run: pwsh ./build.ps1 all
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: VSIX
        path: '*.vsix'

  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: NuGet
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
